#ifndef COLORS_H
#define COLORS_H
#define ARDUINO_SAMD_ZERO
#include "FastLED.h"

#define LED_CONTROLLER WS2812B
#define COLOR_ORDER GRB


static const uint8_t NUMBER_OF_LEDS = 192;
static const uint8_t BRIGHTNESS = 255 * 0.3;
static const uint8_t LED_STRIP_DATA_PIN = 3;
static const uint8_t NUMBER_OF_DESIGNS = 4;

enum Color_index{
	BLACK = 0,
	WHITE = 1,
	RED = 2,
	GREEN = 3,
	BLUE = 4,
	CYAN = 5,
	MAGENTA = 6,
	YELLOW = 7,
	ORANGE = 8,
	PINK = 9,
	DIM_RED = 10,
	DIM_BLUE = 11,
	DIM_CYAN = 12,
	DIM_YELLOW = 13,
	DIM_ORANGE = 14,
	DARK_CYAN = 15
};

CRGB index_to_color(const uint8_t);

constexpr PROGMEM uint16_t DESIGNS[NUMBER_OF_DESIGNS][3] = {//first is index of start of pattern, second is index of end of pattern, and the third is frame duration (ms)
	{0,0,200},
	{1,1,200},
	{2,2,200},
	{3,11,400}
};

static const uint16_t TOTAL_FRAME_COUNT = DESIGNS[NUMBER_OF_DESIGNS - 1][1] + 1;

constexpr PROGMEM uint8_t FRAMES[TOTAL_FRAME_COUNT][NUMBER_OF_LEDS] = {
    {//First frame of Smile (0)
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK
    },//Last frame of Smile (0)
    {//First frame of Neutral (1)
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK
    },//Last frame of Neutral (1)
    {//First frame of Frown (2)
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK
    },//Last frame of Frown (2)
    {//First frame of Space (3)
        Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK
    },
    {
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, 
        Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK
    },
    {
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK
    },
    {
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, 
        Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK
    },
    {
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK
    },
    {
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, 
        Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::RED, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK
    },
    {
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::RED, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK
    },
    {
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::ORANGE, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::ORANGE, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::ORANGE, Color_index::BLACK, Color_index::ORANGE, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::ORANGE, Color_index::BLACK, Color_index::ORANGE, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::ORANGE, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::ORANGE, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK
    },
    {
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::GREEN, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, 
        Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK, Color_index::BLACK
    }//Last frame of Space (11)
};

#endif
